server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: "192.168.1.115:30279"

# Actuator settings ##################################################
management:
  info.git.mode: full
  server:
    port: 8081
