global:
  postgresql:
    secrets: front-app-postgresql

postgres:
  enabled: true
kafka:
  enabled: true
  provisioning:
    enabled: true
    numPartitions: 32
    replicationFactor: 1
    #topics: [testCommand]

image:
  repository: pattanaik007/front
  tag:  "latest"
  pullPolicy: Always

service:
  type: NodePort

appconfig: |-
  server.port: 8080
  ################### Kafka ##############################
  spring:
    kafka:
      bootstrap-servers:  "front-app-kafka-headless.default.svc.cluster.local:9092"
  ################### Logging settings ###################
  logging:
    level:
      root: WARN
      db.demo: INFO
  management.server.port: 8081
