apiVersion: v2
name: springboot
description: A Helm chart for Kubernetes
type: application
version: 0.1.7
appVersion: "1.16.0"
dependencies:
  - condition: postgres.enabled
    name: postgresql
    version: 11.8.1
    repository: https://charts.bitnami.com/bitnami
  - condition: kafka.enabled
    name: kafka
    repository: https://charts.bitnami.com/bitnami
    version: 18.3.1
