apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "springboot.fullname" . }}
  labels:
    {{- include "springboot.labels" . | nindent 4 }}
data:
  app.conf: |-
{{ .Values.appconfig | indent 4 }}